[package]
name = "chimp_protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { version = "1.0.115" }
url = { workspace = true, features = ["serde"] }
uuid = { workspace = true, features = ["serde"] }
