name: Docs

on:
  push:
  pull_request:

jobs:
  build:
    # Deduplicate jobs from pull requests and branch pushes within the same repo.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.1.1

      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@v1.3.1
        with:
          packages: libopencv-dev clang libclang-dev

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: nightly
          default: true

      - name: Cache Rust Build
        uses: Swatinem/rust-cache@v2.7.1

      - name: Build docs
        uses: actions-rs/cargo@v1.0.3
        with:
          command: doc
          args: >
            --workspace
            --no-deps
            --all-features
            --document-private-items
            --manifest-path backend/Cargo.toml
        env:
          RUSTDOCFLAGS: >
            -D warnings
            -Z unstable-options
            --enable-index-page

      - name: Fix file permissions for pages
        run: chmod -R +rX backend/target/doc

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3.0.0
        with:
          path: backend/target/doc

  publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v4.0.0

      - name: Publish docs to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3.0.1
