name: Schema

on:
  push:
  pull_request:

jobs:
  generate_schema:
    # Deduplicate jobs from pull requests and branch pushes within the same repo.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      matrix:
        service:
          - soakdb_sync
          - pin_packing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3.5.3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          default: true

      - name: Cache Rust Build
        uses: Swatinem/rust-cache@v2.6.0

      - name: Generate Schema
        uses: actions-rs/cargo@v1.0.3
        with:
          command: run
          args: >
            --package ${{ matrix.service }}
            schema
            --path ${{ matrix.service }}.graphql

      - name: Upload Schema Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ matrix.service }}.graphql
          path: ${{ matrix.service }}.graphql
